Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,5 +8,9 @@ jobs:
     
     steps:
       - uses: actions/checkout@v3
+      
       - name: Run a sample github action
         run: echo "this workflow run successfully for this particular action"
+        
+      - name: Simulating error
+        run: echo "error taking place"; exit 1
